# Generated by Django 3.1.3 on 2020-12-12 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0003_auto_20201210_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Conta',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
