# Generated by Django 3.1.3 on 2020-12-12 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0004_auto_20201212_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conta',
            new_name='Perfil',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
