# Generated by Django 3.1.4 on 2020-12-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20201223_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcateg',
            old_name='nome',
            new_name='nomesubcateg',
        ),
    ]
