# Generated by Django 3.1.4 on 2020-12-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20201224_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcateg',
            old_name='nomesubcateg',
            new_name='nome',
        ),
    ]
