# Generated by Django 3.1.3 on 2020-12-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
